### ISSUE TITLE
Angular ER Dashboard sample not visible

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/ERDashboard-Angular#4]
When i try to open the Demo Sample of the Angular ER Dashboard a new link opens and the Sample is not displayed.

link : https://www.infragistics.com/resources/sample-applications/angular-er-dashboard

You need to click LAUNCH SAMPLE.

**Comment by dkamburov** [comment]
Closing with the following commit https://github.com/IgniteUI/ERDashboard-Angular/commit/230167dc00f80ec55d9ef981e14b5497fd610475

**Comment by MikeTechSpeak** [comment]
Did this fix not go live yet? Because through our live website this is essentially still happening. 
https://www.infragistics.com/resources/sample-applications/angular-er-dashboard 

Clicking the Launch Sample button goes here:
https://igniteui.github.io/ERDashboard-Angular/

The only thing ever displayed is :
Loading...

**Comment by dkamburov** [comment]
The reason is different, but the samples are broken so I'm reopening the issue

**Comment by mpavlinov** [comment]
@dkamburov It seems that the issue is fixed. I can open the sample and see the application running.

**Comment by dkamburov** [comment]
Yep, working on my side too
